#pragma 

#include "ChatStruct.h"
#include "LoginStruct.h"
#include "ResponseLoginStruct.h"
#include "ChatControl.h"
#include "PublicMessageStruct.h"
#include "PrivateMessageStruct.h"
#include "SignupStruct.h"
#include "ResponseSignupStruct.h"
#include "UserStatusStruct.h"
#include "LoginNotificationStruct.h"
#include "LogoutNotificationStruct.h"
#include "RequestSendFileStruct.h"
#include "ResponseSendFileStruct.h"
#include "PrivateFileStruct.h"